In [1]:
import numpy as np
ar = np.array([[1,2,3],[4,5,6]])
ar
ar.shape

(2, 3)

In [2]:
ar = np.array([[1, 2, 3], [4, 5, 6]])
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
mat = np.arange(0, 100, 5).reshape(4, 5)
mat

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [15]:
e = np.array([25, 50, 4, 5, 70, 20])
np.max(e)
# np.min(e)
# np.mean(e)
# e.itemsize
# np.sum(e)

np.int64(70)

In [10]:
r = np.zeros(50).reshape(5, 10)
r
rr = np.ones(100).reshape(10, 10)
rr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
s = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
np.random.shuffle(s)
s

array([[10, 11, 12],
       [ 7,  8,  9],
       [ 4,  5,  6],
       [ 1,  2,  3]])