# NumPy Tutorial
NumPy is a powerful numerical computing library in Python. It provides support for large multidimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

## Installation
To install NumPy, use the following command:

In [ ]:
#pip install numpy

## Importing NumPy
To start using NumPy, you need to import it into your Python environment.

In [2]:
import numpy as np

## Creating Arrays
NumPy provides several ways to create arrays, including from Python lists or using built-in functions.

In [2]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([[1, 2, 3], [4, 5, 6]])
print(array1)
print(array2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## Array Properties
NumPy arrays have various properties that help in understanding their structure.

In [3]:
print(array2.shape)  # Dimensions of the array
print(array2.size)   # Total number of elements
print(array2.dtype)  # Data type of elements

(2, 3)
6
int64


## Creating Special Arrays
NumPy provides functions to create arrays with specific values, such as zeros, ones, and ranges.

In [4]:
zeros = np.zeros((3,3))
ones = np.ones((2,4))
identity = np.eye(4)  # Identity matrix
arange_array = np.arange(0, 10, 2)
print(zeros, '\n')
print(ones, '\n')
print(identity, '\n')
print(arange_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[0 2 4 6 8]


## Indexing and Slicing
You can access specific elements, slices, and even modify elements in NumPy arrays.

In [5]:
array = np.array([10, 20, 30, 40, 50])
print(array[0])  # First element
print(array[-1]) # Last element
print(array[1:4]) # Slicing elements

10
50
[20 30 40]


## Reshaping Arrays
NumPy allows you to change the shape of an array without changing its data.

In [6]:
reshaped = np.arange(1, 10).reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Mathematical Operations
NumPy supports element-wise mathematical operations and broadcasting.

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)  # Element-wise addition
print(a * b)  # Element-wise multiplication
print(a ** 2) # Squaring elements

[5 7 9]
[ 4 10 18]
[1 4 9]


## Statistical Functions
NumPy provides various statistical functions like mean, median, and standard deviation.

In [3]:
data = np.array([10, 20, 30, 40, 50, 60])
print(np.mean(data))   # Mean
print(np.median(data)) # Median
print(np.std(data))    # Standard Deviation

35.0
35.0
17.07825127659933


## Generating Random Numbers
NumPy has a built-in random module for generating random numbers.

In [9]:
random_array = np.random.rand(3, 3)  # 3x3 array with random values
print(random_array)

[[0.302466   0.36664425 0.86955158]
 [0.45073256 0.61688103 0.83549405]
 [0.5765342  0.75096602 0.22298238]]


## Saving and Loading Arrays
You can save NumPy arrays to a file and load them later.

In [4]:
np.save('array.npy', array)
loaded_array = np.load('array.npy')
print(loaded_array)

NameError: name 'array' is not defined